### ISSUE TITLE
Incorrect use of username/password on LdapOptionsExtensions.Connect for Visus.DirectoryAuthentication

### ISSUE THREAD

**Issue by Maxhy** [UniStuttgart-VISUS/Visus.LdapAuthentication#10]
**Affected library**
- [ ] Visus.LdapAuthentication
- [x] Visus.DirectoryAuthentication

**Environment**
- Library version 0.8.0
- OS: Windows 11
- .NET: 8
- LDAP Server: OpenLDAP

**Summary**
The use of username/password from method parameters or LdapOptions is inconsistent on Visus.DirectoryAuthentication implementation. On Visus.LdapAuthentication the code is using authentication information passed in parameters where here https://github.com/UniStuttgart-VISUS/Visus.LdapAuthentication/blob/e558e1f3e1780b56c6b89775ae5328c10e38e1b3/Visus.DirectoryAuthentication/LdapOptionsExtensions.cs#L91 and https://github.com/UniStuttgart-VISUS/Visus.LdapAuthentication/blob/e558e1f3e1780b56c6b89775ae5328c10e38e1b3/Visus.DirectoryAuthentication/LdapOptionsExtensions.cs#L97 it is coded to use information from LdapOptions. It doesn't looks right to me.

**Comment by crowbar27** [comment]
Thanks for pointing that out. That is actually critical.

**Comment by crowbar27** [comment]
Fixed in 0.9.0
