### ISSUE TITLE
License header in source files contradicts repository license

### ISSUE THREAD

**Issue by mycroes** [UniStuttgart-VISUS/Visus.LdapAuthentication#6]
The license header in source files is as follows:

```xml
// <copyright file="LdapUserBase.cs" company="Visualisierungsinstitut der Universität Stuttgart">
// Copyright © 2021 - 2023 Visualisierungsinstitut der Universität Stuttgart. Alle Rechte vorbehalten.
// </copyright>
// <author>Christoph Müller</author>
```

_All rights reserved_ isn't exactly what the MIT license states (which is declared as repository license). Personally I favor the simple solution of having only a repository license and optional license headers/files for files/directories that do not conform to the repository copyright and/or license.

**Comment by crowbar27** [comment]
Sorry for the delay, I have been very busy in the past weeks. This project was initially only an internal one and we only made is open source later. I will look into this if I have more time. In the meantime, rest assured that we license it under MIT. This was funded by tax money and we give it to the public.

**Comment by mycroes** [comment]
Thanks!
